
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
  dashboards:
    smart-home-dashboard:
      mode: yaml
      title: "Smart Home Dashboard"
      filename: lovelace-dashboard.yaml
      icon: mdi:home-assistant

# ==============================
# üîî Telegram Notification Setup
# ==============================
telegram_bot:
  - platform: polling
    api_key: "xxxxxxxxxxxxxxxxxxxxxx"   # ‚Üê ‡πÉ‡∏ä‡πâ Token ‡∏à‡∏≤‡∏Å BotFather
    allowed_chat_ids:
      - 99999999   # ‚Üê Chat ID ‡∏Ç‡∏≠‡∏á‡∏Ñ‡∏∏‡∏ì

notify:
  - name: telegram
    platform: telegram
    chat_id: 99999999 # ‚Üê Chat ID ‡∏Ç‡∏≠‡∏á‡∏Ñ‡∏∏‡∏ì


recorder:
  db_url: mysql://admin:Home1122@mariadb/homeassistant?charset=utf8mb4
  commit_interval: 2  # ‡∏ö‡∏±‡∏ô‡∏ó‡∏∂‡∏Å‡∏ó‡∏∏‡∏Å 2 ‡∏ô‡∏≤‡∏ó‡∏µ
  auto_purge: true
  purge_keep_days: 7   # ‡πÄ‡∏Å‡πá‡∏ö log 7 ‡∏ß‡∏±‡∏ô 

history:
  include:
    domains:
      - sensor
      - binary_sensor
      - fan
      - switch

logbook:
  include:
    domains:
      - binary_sensor
      - fan
      - switch
  